Service 498
HadoukenIO/fdc3-service pull request #104
Opened 2019-06-03 20:10 UTC by lesjas

2019-06-03 20:10 UTC, finos-admin commented
Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Leslie J**.
This is most likely caused by a git client misconfiguration; please make sure to:
1. check if your git client is configured with an email to sign commits `git config --list | grep email`
2. If not, set it up using `git config --global user.email email@example.com`
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

2019-06-04 20:44 UTC, nicholasdgoodman requested changes
Only request is the property accessor removals. Otherwise at your discretion.

2019-06-04 20:44 UTC, nicholasdgoodman commented on src/cs-client/OpenFin.FDC3.Client/Connection.cs
>          private static List<KeyValuePair<string, Action<ContextBase>>> intentListeners { get; set; }
Remove property accessors.
Consider `Dictionary<string,Action<ContextBase>>`

2019-06-04 20:44 UTC, nicholasdgoodman commented on src/cs-client/OpenFin.FDC3.Client/DesktopAgent.cs
> +                    Connection.ConnectionInitializationComplete += exception =>
Does this never need to be unsubscribed?

2019-06-04 21:21 UTC, finos-admin commented
Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Leslie J**.
This is most likely caused by a git client misconfiguration; please make sure to:
1. check if your git client is configured with an email to sign commits `git config --list | grep email`
2. If not, set it up using `git config --global user.email email@example.com`
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

2019-06-04 21:23 UTC, finos-admin commented
Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Leslie J**.
This is most likely caused by a git client misconfiguration; please make sure to:
1. check if your git client is configured with an email to sign commits `git config --list | grep email`
2. If not, set it up using `git config --global user.email email@example.com`
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

2019-06-06 15:19 UTC, finos-admin commented
Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Leslie J**.
This is most likely caused by a git client misconfiguration; please make sure to:
1. check if your git client is configured with an email to sign commits `git config --list | grep email`
2. If not, set it up using `git config --global user.email email@example.com`
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

2019-06-11 15:16 UTC, merged